apimServiceName: gitopsprd-rg
namedValues:
  - name: environment
    displayName: gitopsprd
    value: prod
  - name: apiopsvalue
    displayName: apiopsvalue
    keyVault:
      identityClientId: Set if Key Vault authentication happens through a user-assigned managed identity
      secretIdentifier: Url for key vault secret (can be versioned if needed).
loggers:
    - name: apiops-dev-insights
      loggerType: applicationInsights
      description: apiopsapplicationinsights
      resourceId: "/subscriptions/28296629-48b9-4b8c-81f1-35c3ca4fed0a/resourceGroups/gitopsprd-rg/providers/microsoft.insights/components/apim-prod-insights"
      credentials:
        instrumentationKey: "destination environment namevalue key for the application insights goes here. You can use the display name to avoid hard coding the key here e.g. {{Logger-Credentials--62390d98217d201158b4bfb3}}. 
                             The assumption is that the namevalue key is already populated in the target environment. This happens automatically when you associate an application insight to your target apim instance"
      isBuffered: true
diagnostics:
   - name: applicationinsights
     verbosity: Error
     loggerId: "/subscriptions/[Azure subscription id for the target environment goes here]/resourceGroups/[resource group name for the target environment goes here]
        /providers/Microsoft.ApiManagement/service/[apim instance name for the target environment goes here]/loggers/[target environment app insight name goes here. e.g. apim-prod-insights]"
apis:
  - name: "[target api version & revision to apply application insights to e.g. 'my-api', 'my-api-v2', 'my-api-v2;rev=2']"
    diagnostics:
      - name: applicationinsights
        verbosity: Error
        loggerId: "/subscriptions/[Azure subscription id for the target environment goes here]/resourceGroups/[resource group name for the target environment goes here]
        /providers/Microsoft.ApiManagement/service/[apim instance name for the target environment goes here]/loggers/[target environment app insight name goes here. e.g. apim-prod-insights]"
        



        
